Repository selsa-inube/inubekit-text, pull requests merged in 2024-02, with the labels that each got.

#9 Implement new version of `@inubekit foundations`
  package-lock.json
  package.json
  src/Text/Text.stories.tsx
  src/Text/index.tsx
  src/Text/props.ts
  src/Text/styles.js
  src/Text/typography.ts
Labels: major

#10 Release new version inubekit/text 2.0.0
  CHANGELOG.md
Labels: documentation

#11 inube-kit/text: new release 2.0.1
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: documentation, dependencies

#12 Publish new version 2.0.2
  CHANGELOG.md
  package.json
Labels: documentation

#13 Publish new version 2.0.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation, dependencies
